# Exception groups

Have you used #Python 3.11's new ExceptionGroup feature yet?

It allows handling multiple exceptions together ðŸ¤¯

Example below:

```
def do_something():
    exceptions = []

    for i in range(5):
        try:
            if i % 2 == 0:
                raise ValueError(f"An error occurred on even number: {i}")
            else:
                raise TypeError(f"An error occurred on odd number: {i}")
        except (ValueError, TypeError) as e:
            exceptions.append(e)

    if exceptions:
        raise ExceptionGroup("Multiple errors occurred", exceptions)


try:
    do_something()
except ExceptionGroup as eg:
    print("Caught an exception group:")
    for ex in eg.exceptions:
        print(f" - {type(ex).__name__}: {ex}")

"""
$ python3.11 script.py
Caught an exception group:
 - ValueError: An error occurred on even number: 0
 - TypeError: An error occurred on odd number: 1
 - ValueError: An error occurred on even number: 2
 - TypeError: An error occurred on odd number: 3
 - ValueError: An error occurred on even number: 4
"""
```

#exceptions #python311
